version: '3.8'

services:
  strapi-service:
    image: ashniike/d2strapi  # Use the Docker image from Docker Hub
    container_name: strapi-app
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "1337:1337"
    depends_on:
      - db-service

  db-service:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - strapi-db-data:/var/lib/postgresql/data

volumes:
  strapi-db-data:
    driver: local
